### ISSUE TITLE
Feature Request: Support Custom send2ereader Instances

### ISSUE THREAD

**Issue by devnullv0id** [doen1el/calibre-web-companion#36]
Hi! Thanks for the awesome app.

Right now, the app uses the public send2ereader instance at https://send.djazz.se/, which works great. But it would be really helpful if we could configure a custom send2ereader URL for those of us running self-hosted instances.

Feature idea:

- Add a setting to specify a custom send2ereader base URL.

- Default to https://send.djazz.se/ if no custom URL is set.

- Update the URL in the "Send" dialog if a custom address is set

This would make the app more flexible and privacy-friendly for self-hosters.

---

Here is a working docker compose (tested in portainer) for the send2ereader app (credit: https://github.com/daniel-j/send2ereader) :

```
version: "3.8"

services:
  send2ereader:
    build:
      context: https://github.com/daniel-j/send2ereader.git
      dockerfile: Dockerfile
    container_name: send2ereader
    restart: unless-stopped
    ports:
      - 3001:3001
    labels:
      - "com.centurylinklabs.watchtower.enable=false" # Disable watchtower update lookup. The lookup will fail since it's build from git and not deployed from a registry. 

```
Thanks for considering!
